In [1]:
import pickle

In [1]:
import numpy as np

In [25]:
np.exp(-0.02*100)

0.1353352832366127

In [5]:
raw_history={}
output = open("/data/uab-giq/scratch/matias/data-vans/XXZ/N2_g1.0J1.0_quiet/run_66/raw_history.pkl", "wb")
pickle.dump(raw_history, output)
output.close()

In [6]:
raw_history

{}

In [16]:
with open("/data/uab-giq/scratch/matias/data-vans/XXZ/N2_g1.0J1.0_quiet/run_66/evolution.pkl" ,"rb") as h:
    rr = pickle.load(h)

In [17]:
rr

{0: [(0, 0): ───Rx(-1.87π)───@───Rz(1.56π)────Rx(0.698π)───Rz(-1.75π)───@───X───Rz(1.67π)───Rx(1.57π)────Rz(0.901π)───X───Rx(1.03π)────
                        │                                          │   │                                         │
(0, 1): ───Rx(0.837π)───X───Rz(0.824π)───Rx(0.842π)───Rz(1.59π)────X───@───Rz(0.54π)───Rx(0.253π)───Rz(0.679π)───@───Rx(0.336π)───,
  <tf.Tensor: shape=(), dtype=float32, numpy=-4.7999997>,
  [4, 5, 0, 2, 4, 2, 3, 5, 3, 0, 1, 3, 5, 3, 2, 4, 2, 1, 4, 5],
  {'th_0': 6.689221,
   'th_1': 2.6280794,
   'th_2': 4.9169326,
   'th_3': 2.1933446,
   'th_4': 7.054137,
   'th_5': 2.5892384,
   'th_6': 2.646633,
   'th_7': 4.9925857,
   'th_8': 1.696187,
   'th_9': 0.7960074,
   'th_10': 2.1340735,
   'th_11': 5.2466335,
   'th_12': 4.922024,
   'th_13': 2.8296602,
   'th_14': 3.2254295,
   'th_15': 1.0570234},
  <tf.Tensor: shape=(), dtype=float32, numpy=-4.7999997>],
 1: [(0, 0): ───Rx(1.84π)───@───Rz(1.55π)───Rx(1.34π)───X───Rz(0.12π)───Rx(1.06π)─

In [14]:
import numpy as np



In [15]:
np.load("/data/uab-giq/scratch/matias/data-vans/XXZ/N2_g1.0J1.0_quiet/run_66/accuracy_to_end.npy")

array([-4.8])